import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const val = 0;
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen homepage">{children}</div>
      </body>
    </html>
  );
}
