import { Inter } from "next/font/google";
import "./globals.css";
import NameProvider from "./context/NameProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const val = 0;
  return (
    <html lang="en">
      <body className={inter.className}>
        <NameProvider>
          <div className="w-screen h-screen homepage">{children}</div>
        </NameProvider>
      </body>
    </html>
  );
}
